version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - modernize
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples/
